StudentiUniMi/website

faq_files/basi_di_dati/basi_di_dati.tex
faq_files/cmds.tex
faq_files/complementi_di_algoritmi_e_strutture_dati/complementi_di_algoritmi_e_strutture_dati.tex
faq_files/diritto_dei_prodotti_digitali/diritto_dei_prodotti_digitali.tex
faq_files/matematica_del_continuo/matematica_del_continuo.tex
faq_files/pkgs.tex
faq_files/programmazione_1/programmazione_1.tex
faq_files/programmazione_2/programmazione_2.tex
faq_files/reti_di_calcolatori/reti_di_calcolatori.tex
faq_files/sistemi_operativi/sistemi_operativi.tex
faq_files/statistica_e_analisi_dei_dati/statistica_e_analisi_dei_dati.tex
faq_files/tecnologie_e_linguaggi_web/tecnologie_e_linguaggi_web.tex
faq_files/template.tex

Aggiornamenti:
1) Invece di \begin{enumerate}, c'è un nuovo environment apposito chiamato QuestionList. Questo permette di gestire in maniera centralizzata gli spazi tra i vari elementi, e in generale di applicare lo stile desiderato
2) Cambiato \domanda in \question, che ora prende due argomenti (la domanda e la risposta). Come sopra, anche qui il comando permette la personalizzazione centralizzata
3) Cambiate tutte le FAQ presenti per usare i nuovi comandi, e fatte modifiche a diverse di queste (come continuo e prog1) per formattare meglio e/o aggiungere materiale

New template

---

src/App.tsx
src/Courses.tsx
src/views/AdditionalGroupsView.tsx

La decisione finale è stata quella di lasciare dipartimento e corso di laurea in italiano per il momento.
Rimosso il -department che era sostanzialmente inutile.

Close: #26 renaming data to english

---

README.md
src/App.css
src/Rules.tsx

Closes #35 
Sezione regolamento aggiornata + overhaul del codice.

Rules section overhaul

---

src/Administrators.tsx
src/App.css
src/Courses.tsx
src/Representatives.tsx
src/Rules.tsx
src/Services.tsx
src/data/Data.json
src/models/Admin.ts
src/models/Degree.ts
src/views/AdditionalGroupsView.tsx
src/views/AdminListView.tsx

Closes #32 , Closes #31 
- Sezione amministratori ora indipendente dai dati e con componenti persona + dropdown per scegliere il cdl
- Aggiunto routing alla sezione rappresentanti e amministratori
- Overhaul globale del codice

Network 3.2

---

src/components/CourseList.tsx
src/components/DegreeInformations.tsx
src/index.css
src/views/AdditionalGroupsView.tsx

zangd jud a stu cos che n funzionv

---

src/data/Data.json

Add Telegram chat ids to Data.json

---

.github/workflows/react.yml

Remove GitHub Pages build from workflow

---

src/themes.ts
src/views/RulesView.tsx

- Primary blue color slightly lighter
- Buttons in rules section now have white text when in dark mode
- Rules MessageBar no more giallo pera
Closes #84

Themes adjustments

---

src/components/CourseList.tsx

I will wait for news about it to know if the problem has actually been solved on all devices. From chrome mobile the problem does not seem to manifest itself anymore.
Closes #87

CourseList is probably fixed

---

src/data/Data.json
src/views/HomeView.tsx

Some adjustments

---

src/data/Data.json
src/data/ExtraGroups.json

Some group adjustments

---

src/data/Data.json
src/data/HomeLinks.json
src/index.scss
src/models/Degree.ts
src/views/CoursesView.tsx

Closes #126 
Closes #125 
Closes #124 
Closes #122

Courses cdl dropdown overhaul + Some adjustments

---

README.md
src/components/Footer.tsx
src/components/HeaderMenu.tsx
src/data/ExtraGroups.json
src/fonts.ts
src/index.css
src/index.scss
src/themes.ts
src/views/AdditionalGroupsView.tsx
src/views/ContributorsView.tsx
src/views/CoursesView.tsx
src/views/HomeView.tsx
src/views/OrganizationView.tsx
src/views/RepresentativesView.tsx
src/views/RulesView.tsx
src/views/ServicesView.tsx

Closes #142 
Closes #130 
Closes #141

Font size and weight fixed in all sections + Some group links fixed + Some adjusments

---

src/components/CourseList.tsx
src/data/Services.json
src/index.css
src/index.scss
src/views/HomeView.tsx
src/views/RulesView.tsx

Closes #155 
Closes #156
Adjusted some cols max-width.
Updated some icons.

#155 and #156

---

src/components/Footer.tsx
src/data/Data.json
src/views/ServicesView.tsx

Closes #167 
Closes #165 
Closes #164

Removed borders after click on services cards + Some adjustments

---

src/data/Data.json

Fix "Analisi e gestione del rischio" group link

---

package-lock.json
package.json
src/components/CourseItem.tsx
src/components/CourseList.tsx
src/data/Data.json
src/index.css
src/index.scss
src/themes.ts
src/views/RulesView.tsx

Added Material UI Chips in course cards + Rules section adjusted

---

src/components/DegreeInformations.tsx
src/data/Contributors.json
src/data/Services.json
src/views/OrganizationView.tsx
src/views/ServicesView.tsx

Services section updated

---

src/components/CourseItem.tsx
src/components/ExtraGroup.tsx
src/data/Data.json
src/index.css
src/index.scss
src/views/HomeView.tsx

Global cards overhaul + Removed last slider

---

src/data/Services.json
src/models/Service.ts
src/views/OrganizationView.tsx
src/views/ServicesView.tsx

Add Labels to Services Card + Global informations moved to Organization

---

README.md
public/svg/react.svg
public/svg/telegram.svg
public/svg/typescript.svg

Readme overhaul

---

package-lock.json
package.json
src/components/CourseItem.tsx
src/data/CanMembers.json
src/data/Faqs.json
src/index.css
src/index.scss
src/models/CanMember.ts
src/models/Faq.ts
src/services/Requests.ts
src/views/ContributorsView.tsx
src/views/HomeView.tsx
src/views/OrganizationView.tsx
src/views/RulesView.tsx
src/views/ServicesView.tsx

Closes #189 
Closes #186 
Closes #188

Homepage FAQs + Global adjustments

---

src/components/CourseItem.tsx
src/components/ExtraGroup.tsx
src/index.css
src/index.scss
src/views/AdditionalGroupsView.tsx

Added chips to cards and enhanced their description

---

src/components/AdminsList.tsx
src/components/CourseList.tsx
src/components/DegreeInformations.tsx
src/components/RepresentativesList.tsx
src/data/Contributors.json
src/data/Data.json
src/data/Faqs.json
src/index.css
src/index.scss
src/models/Degree.ts
src/models/Redirect.ts
src/views/ContributorsView.tsx
src/views/CoursesView.tsx

Courses section restructured and minor adjustments

---

src/components/AdminsList.tsx
src/components/CourseList.tsx
src/data/CanMembers.json
src/models/CanMember.ts
src/views/OrganizationView.tsx

Message of groups / administrators not found and PersonaImage adjusted

---

package-lock.json
package.json
src/components/Footer.tsx
src/data/Data.json
src/views/ContributorsView.tsx
src/views/HomeView.tsx

Closes #205 
Closes #202 
Closes #204

Added slider for "Alloggi" to homepage + Some adjustments

---

package-lock.json
package.json
src/data/Rules.json
src/index.css
src/index.scss
src/models/Rule.ts
src/services/Requests.ts
src/views/HomeView.tsx
src/views/OrganizationView.tsx
src/views/RulesView.tsx

Rules section redesign and other section adjustments

---

src/components/AdminsList.tsx
src/components/ExtraGroup.tsx
src/components/HeaderMenu.tsx
src/components/RepresentativesList.tsx
src/data/CanMembers.json
src/data/Data.json
src/index.css
src/index.scss
src/palettes.ts
src/slider.css
src/slider.scss
src/themes.ts
src/views/CoursesView.tsx
src/views/HomeView.tsx
src/views/MainView.tsx
src/views/RulesView.tsx

Color palettes in settings are now available

---

src/data/Data.json

Changed the Programmazione Web e Mobile (cdl: Sicurezza dei Sistemi e delle Reti triennale) Telegram group link to the Tecnologie e Linguaggi per il Web (cdl: Informatica triennale) one.

Changed PWM group link to the TLW one

---

src/data/CanMembers.json
src/data/Data.json

Network members adjusted

---

src/data/Faqs.json
src/data/Rules.json
src/data/Services.json
src/services/LocalizationService.ts
src/views/ContributorsView.tsx
src/views/HomeView.tsx
src/views/RulesView.tsx

Some translation and components adjustments

---

src/components/HeaderMenu.tsx
src/data/ExtraGroups.json
src/services/LocalizationService.ts
src/views/HomeView.tsx

Closes #227 
Try to fix navigator language bug reported by @ManueleDentello

Main group link changed to @unimichat

---

src/components/HeaderMenu.tsx
src/services/Utils.ts

Expiration date of cookies set to 90 days

---

src/data/Data.json
src/services/LocalizationService.ts

Added "Sicurezza delle architetture orientate ai servizi" group to magistrale_informatica

---

package-lock.json
package.json
public/index.html
public/robots.txt
src/components/HeaderMenu.tsx
src/components/Message.tsx
src/index.scss
src/models/ILocalizationStrings.ts
src/services/LocalizationService.ts
src/services/themes.ts
src/views/ContentView.tsx
src/views/GroupsView.tsx
src/views/MainView.tsx

- Fixed some bugs reported in the last days.
- Created robots.txt for better SEO.
- Usage of react-helmet to dinamically update title of the pages.
Closes #273 
Closes #272 
Closes #267
Closes #270
Closes #268

React-helmet for dynamic titles and descriptions

---

src/data/ExtraGroups.json
src/views/ContentView.tsx
src/views/GroupsView.tsx

SEO Adjustments

---

src/components/Groups/AdditionalGroup.tsx
src/components/Groups/AdditionalGroups.tsx
src/components/Groups/GroupList.tsx
src/components/Home/FirstSection.tsx
src/components/Home/FourthSection.tsx
src/components/Home/SecondSection.tsx
src/components/Home/ThirdSection.tsx
src/data/Faqs.json
src/data/Rules.json
src/data/UniversityLinks.json
src/index.scss
src/models/ILocalizationStrings.ts
src/services/LocalizationService.ts
src/services/palettes.ts
src/services/themes.ts
src/views/GroupsView.tsx
src/views/HomeView.tsx
src/views/OrganizationView.tsx
src/views/RulesView.tsx
src/views/UniversityView.tsx

- I fixed some bugs and added toggle for group filters;
- Palettes have now correct colors (fixed bug reported by @eduardperreca);
- Rules section adjusted as requested by @SteveontheMoon;
- Added Mroik to devs.
Closes #274 
Closes #284 
Closes #283 
Closes #282 
Closes #279
Closes #281
Closes #286

Palettes improvements and group filters toggle

---

src/components/Groups/Autocomplete.tsx
src/components/Groups/Autocomplete_types.ts
src/components/Groups/GroupList.tsx
src/components/HeaderMenu.tsx
src/models/ILocalizationStrings.ts
src/services/LocalizationService.ts
src/views/GroupsView.tsx

- Group filters now behave correctly;
- Progress in #265 (fixed text initialization via degree url);
- Progress in #297 (added a button to reset the groups section content).
Closes #294 
Closes #146
Closes #292

Several adjustments and bug fixes

---

src/components/Footer/Footer.tsx
src/views/OrganizationView.tsx
src/views/UniversityView.tsx

Removed quanto-manca.it from footer links and other adjustments

---

package-lock.json
src/components/Footer/Footer.tsx
src/components/Header/Header.tsx
src/components/Header/HeaderMenu.tsx
src/index.scss
src/models/ILocalizationStrings.ts
src/services/LocalizationService.ts
src/services/Requests.ts

Header overhaul

---

src/components/Home/SecondSection.tsx
src/components/Home/ThirdSection.tsx
src/models/ILocalizationStrings.ts
src/services/LocalizationService.ts

Overleaf redirect

---

components/Groups/GroupItem.tsx
components/Groups/GroupList.tsx
models/Models.ts
pages/courses/[slug].tsx
pages/university.tsx
styles/index.scss

I did some fixes on undefined values for API models too
Closes #359 
Closes #357 
Closes #361

Custom behaviour for card titles

---

components/Courses/AdminsList.tsx
components/University/RepresentativesList.tsx
pages/organization.tsx
styles/index.scss

Fixed avatar SSR issues

---

components/Home/Ad.tsx
pages/index.tsx

If you want to add it to the other sections too just add the <Ad /> component at the start of each one

Homepage ad

---

data/NetworkMembers.json
pages/organization.tsx

On https://studentiunimi.it/organization it doesn't show the correct propic

Fix propic for Mroik
